[package]
name = "gliden64"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
lazy_static = "1.4"
log = "0.4"
num-derive = "0.3"
num-traits = "0.2"

[build-dependencies]
bindgen = "0.59"
cmake = "0.1"
